#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Thiết lập IPv6
xoa_ipv6() {
    echo "Xoá Tất Cả IPv6 Củ..."
    ip -6 addr flush dev eth0
    ip -6 addr flush dev ens33
}
xoa_ipv6

# Cài đặt các gói cần thiết
yum install make wget curl jq git iptables-services -y

# Lấy tên interface mạng
NETWORK_INTERFACE_NAME=$(ip route get 8.8.8.8 | sed -nr 's/.*dev ([^\ ]+).*/\1/p')
echo "MTU=1500" >> /etc/sysconfig/network-scripts/ifcfg-$NETWORK_INTERFACE_NAME

# Kiểm tra hệ thống có sử dụng YUM hay không
YUM=$(which yum)

if [ "$YUM" ]; then
    echo > /etc/sysctl.conf
    tee -a /etc/sysctl.conf <<EOF
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.all.disable_ipv6 = 0
EOF
    sysctl -p

    interfaces=$(ip -o link show | awk -F': ' '{print $2}')
    IPC=$(curl -4 -s icanhazip.com | cut -d"." -f3)
    IPD=$(curl -4 -s icanhazip.com | cut -d"." -f4)
    for iface in $interfaces; do
        if [ $IPC == 4 ]; then
            tee -a /etc/sysconfig/network-scripts/ifcfg-$iface <<-EOF
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6ADDR=2403:6a40:0:40::$IPD:0000/64
IPV6_DEFAULTGW=2403:6a40:0:40::1
EOF
        elif [ $IPC == 5 ]; then
            tee -a /etc/sysconfig/network-scripts/ifcfg-$iface <<-EOF
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6ADDR=2403:6a40:0:41::$IPD:0000/64
IPV6_DEFAULTGW=2403:6a40:0:41::1
EOF
        elif [ $IPC == 244 ]; then
            tee -a /etc/sysconfig/network-scripts/ifcfg-$iface <<-EOF
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6ADDR=2403:6a40:2000:244::$IPD:0000/64
IPV6_DEFAULTGW=2403:6a40:2000:244::1
EOF
        else
            tee -a /etc/sysconfig/network-scripts/ifcfg-$iface <<-EOF
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6ADDR=2403:6a40:0:$IPC::$IPD:0000/64
IPV6_DEFAULTGW=2403:6a40:0:$IPC::1
EOF
        fi
    done

    service network restart

# Nếu không sử dụng YUM thì kiểm tra sử dụng apt (Ubuntu)
else
    ipv4=$(curl -4 -s icanhazip.com)
    IPC=$(curl -4 -s icanhazip.com | cut -d"." -f3)
    IPD=$(curl -4 -s icanhazip.com | cut -d"." -f4)
    INT=$(ls /sys/class/net | grep e)
    if [ "$IPC" = "4" ]; then
        IPV6_ADDRESS="2403:6a40:0:40::$IPD:0000/64"
        GATEWAY="2403:6a40:0:40::1"
    elif [ "$IPC" = "5" ]; then
        IPV6_ADDRESS="2403:6a40:0:41::$IPD:0000/64"
        GATEWAY="2403:6a40:0:41::1"
    elif [ "$IPC" = "244" ]; then
        IPV6_ADDRESS="2403:6a40:2000:244::$IPD:0000/64"
        GATEWAY="2403:6a40:2000:244::1"
    else
        IPV6_ADDRESS="2403:6a40:0:$IPC::$IPD:0000/64"
        GATEWAY="2403:6a40:0:$IPC::1"
    fi
    interface_name="$INT"  # Tên giao diện mạng
    ipv6_address="$IPV6_ADDRESS"
    gateway6_address="$GATEWAY"
    netplan_path="/etc/netplan/50-cloud-init.yaml"  # Đường dẫn tập tin cấu hình Netplan

    netplan_config=$(cat "$netplan_path")
    new_netplan_config=$(sed "/gateway4:/i \ \ \ \ \ \ \ \ \ \ \ \ - $ipv6_address" <<< "$netplan_config")
    new_netplan_config=$(sed "/gateway4:.*/a \ \ \ \ \ \ \ \ \ \ \ \ gateway6: $gateway6_address" <<< "$new_netplan_config")

    echo "$new_netplan_config" > "$netplan_path"

    sudo netplan apply
fi

echo 'IPv6 đã được cấu hình thành công!'


# Tự động phát hiện giao diện mạng
auto_detect_interface() {
    IFCFG=$(ip -o link show | awk -F': ' '$3 !~ /lo|vir|^[^0-9]/ {print $2; exit}')
}

# Tạo địa chỉ IPv6 và cấu hình iptables
gen_ipv6_64() {
    rm "$WORKDIR/ipv6.txt" 2>/dev/null || true
    count_ipv6=1
    while [ "$count_ipv6" -le "$MAXCOUNT" ]; do
        array=( 1 2 3 4 5 6 7 8 9 0 a b c d e f )
        ip64() {
            echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
        }
        echo "$IP6:$(ip64):$(ip64):$(ip64):$(ip64)" >> "$WORKDIR/ipv6.txt"
        let "count_ipv6 += 1"
    done
}

# Cài đặt và cấu hình 3proxy
install_3proxy() {
    echo "Đang cài đặt 3proxy..."
    git clone https://github.com/z3apa3a/3proxy
    cd 3proxy || exit 1
    ln -s Makefile.Linux Makefile >/dev/null 2>&1
    make >/dev/null 2>&1
    sudo make install >/dev/null 2>&1
    cd "$WORKDIR" || exit 1
    sudo cp -R 3proxy/scripts/init.d/3proxy /etc/init.d/
    sudo chmod +x /etc/init.d/3proxy
    chkconfig 3proxy on
    service 3proxy start
    systemctl daemon-reload
    systemctl enable 3proxy
    echo "* hard nofile 999999" >>  /etc/security/limits.conf
    echo "* soft nofile 999999" >>  /etc/security/limits.conf
    echo "net.ipv6.conf.${NETWORK_INTERFACE_NAME}.proxy_ndp=1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.all.proxy_ndp=1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.default.forwarding=1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
    echo "net.ipv6.ip_nonlocal_bind = 1" >> /etc/sysctl.conf
    sysctl -p
    systemctl stop firewalld
    systemctl disable firewalld
    ulimit -n 65535
}

# Tạo cấu hình 3proxy
gen_3proxy_cfg() {
    echo "daemon"
    echo "maxconn 10000"
    echo "nserver 1.1.1.1"
    echo "nserver 8.8.4.4"
    echo "nserver [2606:4700:4700::1111]"
    echo "nserver [2606:4700:4700::1001]"
    echo "nserver 2001:4860:4860::8888"
    echo "nserver 2001:4860:4860::8844"
    echo "nscache 65536"
    echo "timeouts 1 5 30 60 180 1800 15 60"
    echo "setgid 65535"
    echo "setuid 65535"
    echo "stacksize 6291456"
    echo "flush"
    echo "auth none"
    echo "allow 127.0.0.1"

    port="$START_PORT"
    while read -r ip; do
        echo "proxy -6 -n -a -p$port -i$IP4 -e$ip"
        ((port+=1))
    done < "$WORKDIR/ipv6.txt"
}

# Tạo lệnh ifconfig cho IPv6
gen_ifconfig() {
    while read -r line; do
        echo "ifconfig $IFCFG inet6 add $line/64"
    done < "$WORKDIR/ipv6.txt"
}

# Xuất cấu hình ra tập tin văn bản
export_txt() {
    port="$START_PORT"
    for ((i=1; i<=$MAXCOUNT; i++)); do
        echo "$IP4:$port"
        ((port+=1))
    done
}

# Kiểm tra quyền root và khởi động chính script
if [ "$(id -u)" != '0' ]; then
    echo 'Lỗi: Script này cần chạy với quyền root'
    exit 1
fi

# Các biến chính
WORKDIR="/home/proxy"
MAXCOUNT="2000"  # Thay thế bằng số lượng IPv6 cần tạo
mkdir -p "$WORKDIR"
chmod -R 777 "$WORKDIR"
auto_detect_interface


    IP4=$(curl -4 -s icanhazip.com)
    IP6=$(curl -6 -s icanhazip.com | cut -f1-4 -d':')
    main_interface=$(ip route get 8.8.8.8 | awk '{print $5}')
    echo "[OKE]: Thành công"
    echo "IPv4: $IP4"
    echo "IPv6: $IP6"
    echo "Giao diện mạng chính: $main_interface"
else
    echo "[ERROR]: Thất bại!"
    exit 1
fi

IFCFG="$main_interface"
WORKDIR="/home/proxy"
START_PORT=10000
MAXCOUNT=2000

# Tạo địa chỉ IPv6 và cấu hình
echo "Đang tạo $MAXCOUNT IPv6 > ipv6.txt"
gen_ipv6_64
echo "Đang tạo IPV6 gen_ifconfig.sh"
gen_ifconfig > "$WORKDIR/boot_ifconfig.sh"

# Cài đặt 3proxy và cấu hình
systemctl disable --now firewalld
service iptables stop
gen_3proxy_cfg > /etc/3proxy/3proxy.cfg
service 3proxy restart

# Xuất cấu hình ra tập tin văn bản
echo "Xuất $IP4.txt"
export_txt > "$WORKDIR/$IP4.txt"

# Tạo script xoay để cập nhật địa chỉ IPv6
gen_xoay() {
    cat <<EOF > "$WORKDIR/xoay.sh"
#!/bin/bash
echo "Đang tạo $MAXCOUNT IPv6 > ipv6.txt"
gen_ipv6_64
echo "Đang tạo IPV6 gen_ifconfig.sh"
gen_ifconfig > "$WORKDIR/boot_ifconfig.sh"
echo "Khởi động lại 3proxy"
gen_3proxy_cfg > /etc/3proxy/3proxy.cfg
service 3proxy restart
echo "Đã đặt lại địa chỉ IP"
EOF
    chmod +x "$WORKDIR/xoay.sh"
}
gen_xoay

echo "Cấu hình Xoay thành công"

cat >>/etc/rc.local <<EOF
#!/bin/bash
systemctl start NetworkManager.service
ifup $main_interface
killall 3proxy
service 3proxy start
bash ${WORKDIR}/boot_iptables.sh
bash ${WORKDIR}/boot_ifconfig.sh
ulimit -n 65535
/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg &
Restart=always
RestartSec=5   # Thời gian chờ giữa các lần khởi động lại (tùy chọn)
ExecStop=/bin/kill -SIGINT $MAINPID   # Lệnh dừng dịch vụ 3proxy
EOF

echo "Tổng số IPv6 hiện tại:"
ip -6 addr | grep inet6 | wc -l
upload_proxy
