#!/bin/sh

if [ "x$(id -u)" != 'x0' ]; then
    echo 'Lỗi: Mã này chỉ có thể chạy bởi root'
    exit 1
fi

echo
echo ====================================
echo -e    "\e[1;226;42m Thiết lập và cấu hình lại mạng\e[0m"
echo ====================================
echo
service network restart
ulimit -u unlimited -n 999999 -s 16384
systemctl stop firewalld

random() {
    tr </dev/urandom -dc A-Za-z0-9 | head -c5
    echo
}

array=(1 2 3 4 5 6 7 8 9 0 a b c d e f)
#/64 network
gen64() {
    ip64() {
        echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
    }
    echo "$1:$(ip64):$(ip64):$(ip64):$(ip64)"
}

#/48 network
gen64_48() {
    ip64() {
        echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
    }
    echo "$1:$(ip64):$(ip64):$(ip64):$(ip64):$(ip64)"
}

install_3proxy() {
      
    echo      
    echo ====================================
    echo -e    "\e[1;226;42m Đang cài đặt 3proxy\e[0m"
    echo ====================================
    echo
   
    install_3proxy() {
        echo "Đang cài đặt 3proxy"
        URL="https://github.com/z3APA3A/3proxy/archive/3proxy-0.8.6.tar.gz"
        wget -qO- $URL | bsdtar -xvf-
        cd 3proxy-3proxy-0.8.6
        make -f Makefile.Linux
        mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
        cp src/3proxy /usr/local/etc/3proxy/bin/
        cd $WORKDIR
    }

    gen_3proxy() {
        cat <<EOF
        daemon
        maxconn 10000
        nserver 1.1.1.1
        nserver [2606:4700:4700::1111]
        nserver [2606:4700:4700::1001]
        nserver [2001:4860:4860::8888]
        nscache6 65536
        nscache 65536
        timeouts 1 5 30 60 180 1800 15 60
        setgid 65535
        setuid 65535
        flush
        auth strong
        users $(awk -F "/" 'BEGIN{ORS="";} {print $1 ":CL:" $2 " "}' ${WORKDATA})
        $(awk -F "/" '{print "auth strong\n" \
        "allow " $1 "\n" \
        "proxy -6 -n -a -p" $4 " -i" $3 " -e"$5"\n" \
        "flush\n"}' ${WORKDATA})
EOF
    }

upload_proxy() {
    zip proxy.zip proxy.txt
    URL=$(curl -s --upload-file proxy.zip https://transfer.sh/proxy.zip)

    echo "Proxy đã sẵn sàng! Định dạng LOGIN:PASS@IP:PORT"
    echo "Tải tệp nén từ: ${URL}"
}

    gen_data() {
        seq $FIRST_PORT $LAST_PORT | while read port; do
            echo "vlt$(random)/pass$(random)/$IP4/$port/$(gen64 $IP6)"
        done
    }

    gen_data_48() {
        seq $FIRST_PORT $LAST_PORT | while read port; do
            echo "usr$(random)/pass$(random)/$IP4/$port/$(gen64 $IP6)"
        done
    }

    gen_iptables() {
        cat <<EOF
        $(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA}) 
EOF
    }


    gen_ifconfig() {
        cat <<EOF
        $(awk -F "/" '{print "ifconfig eth0 inet6 add " $5 "/64"}' ${WORKDATA})
EOF
    }

    echo
    echo ====================================
    echo -e    "\e[1;226;42m Đang cài đặt công cụ\e[0m"
    echo ====================================
    echo
    yum -y update
    yum -y groupinstall "Development Tools"
    yum -y install gcc zlib-devel openssl-devel readline-devel ncurses-devel wget tar zip dnsmasq net-tools iptables-services system-config-firewall-tui nano iptables-services bsdtar


    echo
    echo ====================================
    echo -e    "\e[1;226;42m Đang cài đặt 3proxy\e[0m"
    echo ====================================
    echo
    install_3proxy

    echo "Thư mục làm việc = /root/proxy"
    WORKDIR="/root/proxy"
    WORKDATA="${WORKDIR}/data.txt"
    mkdir $WORKDIR && cd $_

    IP4=$(curl -4 -s icanhazip.com)
    IP6=$(curl -6 -s icanhazip.com | cut -f1-4 -d':')

    echo "Địa chỉ IP nội bộ = ${IP4}. Phụ trợ ngoại bộ cho IP6 = ${IP6}"

    echo
    echo ====================================
    echo -e    "\e[1;226;42m IP nội bộ = ${IP4}\e[0m"
    echo -e    "\e[1;226;42m Tiền tố hệ thống cho IP6 = ${IP6}\e[0m"
    echo Vui lòng kiểm tra tiền tố này hai lần, cho mạng /64 nó trông giống như 2604:180:2:11c7, cho /48 giống như 2604:180:2
    echo ====================================
    echo
      

    read -r -p "Bạn muốn tạo bao nhiêu proxy? Ví dụ 500:  " COUNT

    FIRST_PORT=10000
    LAST_PORT=$(($FIRST_PORT + $COUNT))

    gen_data >$WORKDIR/data.txt
    gen_iptables >$WORKDIR/boot_iptables.sh
    gen_ifconfig >$WORKDIR/boot_ifconfig.sh

    gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg
    start_3proxy() {
    /usr/local/etc/3proxy /usr/local/etc/3proxy/3proxy.cfg
} 

start_3proxy

echo pidfile /usr/local/etc/3proxy/3proxy.pid

echo daemon
echo maxconn 3333
echo nserver 1.1.1.1
echo nserver [2606:4700:4700::1111]
echo nserver [2606:4700:4700::1001]
echo nserver [2001:4860:4860::8888]
echo nscache6 65536
echo nscache 65536
echo stacksize 6000
echo timeouts 1 5 30 60 180 1800 15 60
echo setgid 65535
echo setuid 65535
echo flush

# HTTP(S) proxy
echo "auth iponly"
echo "allow * 14.224.163.75"

port=30000
count=1
for i in `cat ip.list`; do
    echo "proxy -6 -n -a -p$port -i127.0.0.1 -e$i"
    ((port+=1))
    ((count+=1))
    if [ $count -eq 10001 ]; then
        exit
    fi
done
