#!/bin/bash

# Hàm log
function log() {
   echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") [install] $1"
}

# Kiểm tra hệ điều hành và trình quản lý gói (Ubuntu/Debian vs CentOS/RHEL)
if [ -f /etc/lsb-release ] || [ -f /etc/debian_version ]; then
    OS="ubuntu"
    PKG_MGR="apt"
    UFW="ufw"
elif [ -f /etc/redhat-release ]; then
    OS="centos"
    PKG_MGR="yum"
    UFW="firewalld"
else
    log "Unsupported operating system."
    exit 1
fi

log "Detected operating system: $OS"

# Cập nhật và cài đặt các gói cần thiết
log "Installing Tor..."
if [ "$OS" == "ubuntu" ]; then
    apt-get update && apt install -y tor wget sudo nano curl systemd gnupg
    apt-transport-https net-tools jq ufw firewalld && apt-get clean
elif [ "$OS" == "centos" ]; then
    sudo yum install epel-release -y
    sudo yum install tor firewalld curl net-tools -y
    sudo systemctl start firewalld
    sudo systemctl enable firewalld
fi

# Cấu hình firewall mở các cổng cần thiết
log "Configuring firewall..."
if [ "$OS" == "ubuntu" ]; then
    ufw allow from 172.17.0.0/16 to 192.168.1.0/24
    ufw allow from 192.168.1.0/24 to 172.17.0.0/16
    ufw allow 1:65535/tcp
    ufw allow 1:65535/udp
    ufw allow proto tcp from 192.168.1.0/24 to any port 1:65535
    ufw allow 9051/tcp
    ufw allow proto udp from 192.168.1.0/24 to any port 1:65535
    ufw allow 200000:34931/tcp
    ufw reload
    sudo ufw reload
elif [ "$OS" == "centos" ]; then
    systemctl start firewalld
    systemctl enable firewalld
    firewall-cmd --permanent --add-port=53/tcp
    firewall-cmd --permanent --add-port=9050/tcp
    firewall-cmd --permanent --add-port=9051/tcp
    firewall-cmd --permanent --add-port=9052/tcp
    firewall-cmd --permanent --add-port=9053/tcp
    firewall-cmd --permanent --add-port=10000-40000/tcp
    firewall-cmd --reload
fi

# Cài đặt cấu hình cho Tor
log "Downloading new Tor configuration..."
sudo rm -f /etc/tor/torrc
sudo curl -o /etc/tor/torrc https://volamtuan.github.io/torrc

# Khởi động lại dịch vụ Tor
log "Restarting Tor service..."
systemctl restart tor
systemctl enable tor
systemctl start tor

log "Installation and configuration completed successfully!"

# Kiểm tra trạng thái của các cổng đang mở
echo "Các cổng đang mở:"
netstat -tuln | grep LISTEN

# Chạy thêm script ce.sh nếu cần
echo "Check Proxy..."
curl -x http://localhost:10000 https://ifconfig.me
curl -x http://localhost:20000 https://ifconfig.me
curl -x http://localhost:30000 https://ifconfig.me
curl -x http://localhost:40000 https://ifconfig.me

wget -q http://volamtuan.github.io/ce.sh && chmod +x ce.sh && bash ce.sh

